sudo: false
language: node_js
script:
- npm run istanbul
after_success:
- npm run coveralls
node_js:
- stable
deploy:
  provider: npm
  email: ivan.goncharov.ua@gmail.com
  api_key:
    secure: W14ErJK0/FerreriIeadLqbaXbHxRAXGWP0EMYgqvsvIrEqr8xjgyifca+F6a9BOBB+eo1wOcT1RA8YMhGlC0EztlM9IrCCBMvIZbHvAKyKA0NKRm5MF+jo7Z1znMKbI0LDobKkvQIMGrqX8EcRK32Khb6Fe/zQeM/p6OeCN+6I=
  on:
    tags: true
    repo: apigee-127/swagger-converter
  skip_cleanup: true
